[project]
authors = ["Mikkel Roald-Arbøl <github.ggb9a@simplelogin.co>"]
channels = ["conda-forge"]
name = "academicv"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]
compile = 'typst compile template/template.typ --root ~/Filen/Projects/templates/academicv'

[dependencies]
typst = ">=0.13.1,<0.14"
